### ISSUE TITLE
how to print current webView?

### ISSUE THREAD

**Issue by Saqib92** [BarisCanYesil/capacitor-plugin-printer#5]
As per documentation we need to pass `content` option to print, but is there any way to print current webView?

**Comment by Mendzyy** [comment]
Hi @Saqib92 

I am not quite sure, if this is going to work, but if you would like to try, could you pass `document.documentElement.outerHTML;`  to `content`?

**Comment by BarisCanYesil** [comment]
Unfortunately, there is no direct ‘webView’ print feature in the plugin yet.
