### ISSUE TITLE
PDF Support

### ISSUE THREAD

**Issue by StriderRanger** [BarisCanYesil/capacitor-plugin-printer#6]
Hello,

Can you please add PDF support, like for example taking dataurlstring/base64 format as an input ?

Thanks !

**Comment by BarisCanYesil** [comment]
Hello, I will review your request as soon as possible.

**Comment by BarisCanYesil** [comment]
Hello again,
I added base64 support with version 0.0.5, you can check the README for details.

**Comment by StriderRanger** [comment]
Thank you for your quick response

**Comment by gsttesterdevice** [comment]
> Hello, I am trying to print a base64 value but the plugin is printing the full string. It must not be interpreting my base64 correctly. Any tips?

@BarisCanYesil  kindly look into this
